name: ava_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  intl: ^0.19.0
  logging: ^1.2.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: AtHauss
      fonts:
        - asset: fonts/AtHaussTRIAL-Regular.otf
          weight: 400
        - asset: fonts/AtHaussTRIAL-Semibold.otf
          weight: 600
    - family: AtSlam
      fonts:
        - asset: fonts/AtSlamCnd-Semibold.otf
          weight: 600
